In [1]:
"""                    Computation on NumPy Arrays: Universal Functions                     """

'                    Computation on NumPy Arrays: Universal Functions                     '

In [3]:
# ----- The Slowness of Loops ----- #

In [4]:
import numpy as np
np.random.seed(0)

In [6]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size = 5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [11]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)


1.23 s ± 8.76 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [12]:
# ---- Introducing UFuncs ---- #

In [14]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [15]:
%timeit (1.0 / big_array)

1.42 ms ± 43.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [16]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [20]:
arr = np.arange(9).reshape((3, 3))
2 ** arr

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [21]:
%timeit arr

9.97 ns ± 0.699 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


In [22]:
%timeit np.arange(5) / np.arange(1, 6)

1.73 μs ± 8.74 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [23]:
# ----- Exploring NumPy’s UFuncs ----- #

In [24]:
# Array arithmetic #

In [25]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division


x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [26]:
print("-x =", -x)
print("x ** 2 =", x ** 2)
print("x % 2 =", x % 2)


-x = [ 0 -1 -2 -3]
x ** 2 = [0 1 4 9]
x % 2 = [0 1 0 1]


In [27]:
-(0.5 * x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [33]:
np.add(x, 2)

array([2, 3, 4, 5])

In [34]:
np.add(np.arange(6), np.arange(6, 12))

array([ 6,  8, 10, 12, 14, 16])

In [ ]:
x = np.random.randint(1, 10, (3, 3))
y = np.random.randint(1, 10, (3, 3))

print(f"X: \n{x} \n Y: \n{y}")
np.add(x, y)

X: 
[[9 1 9]
 [3 5 8]
 [8 2 9]] 
 Y: 
[[3 5 7]
 [3 2 4]
 [5 9 8]]


array([[12,  6, 16],
       [ 6,  7, 12],
       [13, 11, 17]], dtype=int32)

In [48]:
x = np.random.randint(1, 10, (3, 3))
y = np.random.randint(1, 10, (3, 3))

print(f"X: \n{x} \n Y: \n{y}")
np.subtract(x, y)

X: 
[[5 3 5]
 [8 7 1]
 [2 5 1]] 
 Y: 
[[7 7 9]
 [4 4 6]
 [4 3 6]]


array([[-2, -4, -4],
       [ 4,  3, -5],
       [-2,  2, -5]], dtype=int32)

In [52]:
x = np.random.randint(1, 10, (3, 3))
y = np.random.randint(1, 10, (3, 3))

print(f"X: \n{x} \n Y: \n{y}")
np.negative(x)

X: 
[[7 9 6]
 [1 2 9]
 [1 8 1]] 
 Y: 
[[3 7 5]
 [8 2 7]
 [5 3 7]]


array([[-7, -9, -6],
       [-1, -2, -9],
       [-1, -8, -1]], dtype=int32)

In [53]:
np.negative(y)

array([[-3, -7, -5],
       [-8, -2, -7],
       [-5, -3, -7]], dtype=int32)

In [63]:
x = np.random.random((3, 3))
y = np.random.random((3, 3))
print(f"X: \n{x} \n Y: \n{y}")
np.multiply(x, y)

X: 
[[0.07816235 0.52343797 0.19610991]
 [0.85040833 0.11088528 0.71995107]
 [0.10650209 0.6744257  0.93646953]] 
 Y: 
[[0.43331847 0.79227384 0.64454763]
 [0.692523   0.97454237 0.97941473]
 [0.81995631 0.01021078 0.13757   ]]


array([[0.03386919, 0.41470621, 0.12640218],
       [0.58892733, 0.10806241, 0.70513068],
       [0.08732706, 0.00688641, 0.12883012]])

In [66]:
x = np.random.randint(1, 10, (3, 3))
y = np.random.randint(1, 10, (3, 3))
print(f"X: \n{x} \n Y: \n{y}")

np.divide(x, y)

X: 
[[7 3 3]
 [2 5 1]
 [8 6 6]] 
 Y: 
[[9 5 6]
 [6 1 4]
 [3 4 5]]


array([[0.77777778, 0.6       , 0.5       ],
       [0.33333333, 5.        , 0.25      ],
       [2.66666667, 1.5       , 1.2       ]])

In [67]:
%timeit np.divide(x, y)

1.16 μs ± 5.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [68]:
x = np.random.randint(1, 10, (3, 3))
y = np.random.randint(1, 10, (3, 3))
print(f"X: \n{x} \n Y: \n{y}")

np.floor_divide(x, y)

X: 
[[4 5 3]
 [9 8 7]
 [3 9 6]] 
 Y: 
[[2 6 9]
 [4 2 6]
 [7 6 4]]


array([[2, 0, 0],
       [2, 4, 1],
       [0, 1, 1]], dtype=int32)

In [69]:
x = np.random.randint(1, 10, (3, 3))
y = np.random.randint(1, 10, (3, 3))
print(f"X: \n{x} \n Y: \n{y}")

np.pow(x, y)

X: 
[[2 6 7]
 [2 7 3]
 [2 7 5]] 
 Y: 
[[8 4 9]
 [3 2 1]
 [7 7 6]]


array([[     256,     1296, 40353607],
       [       8,       49,        3],
       [     128,   823543,    15625]], dtype=int32)

In [71]:
np.sqrt(x)

array([[1.41421356, 2.44948974, 2.64575131],
       [1.41421356, 2.64575131, 1.73205081],
       [1.41421356, 2.64575131, 2.23606798]])

In [72]:
np.sqrt(y)

array([[2.82842712, 2.        , 3.        ],
       [1.73205081, 1.41421356, 1.        ],
       [2.64575131, 2.64575131, 2.44948974]])

In [75]:
np.sin(x)

array([[ 0.90929743, -0.2794155 ,  0.6569866 ],
       [ 0.90929743,  0.6569866 ,  0.14112001],
       [ 0.90929743,  0.6569866 , -0.95892427]])

In [76]:
np.mod(x, y)

array([[2, 2, 7],
       [2, 1, 0],
       [2, 0, 5]], dtype=int32)

In [79]:
print(x)
np.cos(x)

[[2 6 7]
 [2 7 3]
 [2 7 5]]


array([[-0.41614684,  0.96017029,  0.75390225],
       [-0.41614684,  0.75390225, -0.9899925 ],
       [-0.41614684,  0.75390225,  0.28366219]])

In [80]:
print(x)
np.tan(x)

[[2 6 7]
 [2 7 3]
 [2 7 5]]


array([[-2.18503986, -0.29100619,  0.87144798],
       [-2.18503986,  0.87144798, -0.14254654],
       [-2.18503986,  0.87144798, -3.38051501]])

In [81]:
np.std(x)

np.float64(2.165954298846436)

In [82]:
# Absolute value #

In [84]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [89]:
x = np.random.randint(1, 10, (4, 4))
negative = np.negative(x)
negative

array([[-4, -3, -3, -2],
       [-6, -2, -9, -5],
       [-4, -6, -7, -7],
       [-1, -7, -7, -7]], dtype=int32)

In [90]:
np.abs(negative)

array([[4, 3, 3, 2],
       [6, 2, 9, 5],
       [4, 6, 7, 7],
       [1, 7, 7, 7]], dtype=int32)

In [91]:
np.abs(negative) % 2

array([[0, 1, 1, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [93]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

In [94]:
# Trigonometric functions #

In [95]:
theta = np.linspace(0, np.pi, 3)

In [96]:
print("theta =", theta)
print("sin(theta) =", np.sin(theta))
print("cos(theta) =", np.cos(theta))
print("tan(theta) =", np.tan(theta))


theta = [0.         1.57079633 3.14159265]
sin(theta) = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [97]:
x = [-1, 0, 1]
print("x =", x)
print("arcsin(x) =", np.arcsin(x))
print("arccos(x) =", np.arccos(x))
print("arctan(x) =", np.arctan(x))


x = [-1, 0, 1]
arcsin(x) = [-1.57079633  0.          1.57079633]
arccos(x) = [3.14159265 1.57079633 0.        ]
arctan(x) = [-0.78539816  0.          0.78539816]


In [98]:
# Exponents and logarithms #

In [99]:
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))


x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


In [100]:
x = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))


x = [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [101]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))


exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


In [102]:
# Specialized ufuncs #

In [103]:
from scipy import special

x = [1, 5, 10]
print("gamma(x) =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2) =", special.beta(x, 2))


gamma(x) = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2) = [0.5        0.03333333 0.00909091]


In [104]:
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x) =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))


erf(x) = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


In [105]:
# ----- Advanced Ufunc Features ----- #

In [106]:
# Specifying output

In [107]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out = y)
print(y)

[ 0. 10. 20. 30. 40.]


In [108]:
y = np.zeros(10)
np.power(2, x, out = y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [109]:
y[::2] = 2 ** x

In [110]:
# Aggregates #

In [111]:
x = np.arange(1, 6)
np.add.reduce(x)

np.int64(15)

In [112]:
np.multiply.reduce(x)

np.int64(120)

In [113]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [114]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [115]:
# Outer products #

In [116]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])