In [2]:
import numpy as np
np.random.seed(0)

In [3]:
x1 = np.random.randint(10, size = 6)
x2 = np.random.randint(10, size = (3, 4))
x3 = np.random.randint(10, size = (3, 4, 5))

In [4]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [5]:
print("dtype: ", x3.dtype)

dtype:  int32


In [6]:
print("itemsize: ", x3.itemsize, "bytes")
print("nbytes: ", x3.nbytes, "bytes")

itemsize:  4 bytes
nbytes:  240 bytes


In [7]:
"""               Array Indexing: Accessing Single Elements             """

'               Array Indexing: Accessing Single Elements             '

In [8]:
x1

array([5, 0, 3, 3, 7, 9], dtype=int32)

In [9]:
x1[0]

np.int32(5)

In [10]:
x1[4]

np.int32(7)

In [11]:
x1[-1]

np.int32(9)

In [12]:
x1[-2]

np.int32(7)

In [13]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]], dtype=int32)

In [14]:
x2[0, 0]

np.int32(3)

In [15]:
x2[2, 0]

np.int32(1)

In [16]:
x2[2, -1]

np.int32(7)

In [17]:
x2[0, 0] = 12

In [18]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]], dtype=int32)

In [19]:
x1[0] = 3.14
x1

array([3, 0, 3, 3, 7, 9], dtype=int32)

In [20]:
"""                 Array Slicing: Accessing Subarrays            """

'                 Array Slicing: Accessing Subarrays            '

In [21]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
x[:5]

array([0, 1, 2, 3, 4])

In [23]:
x[4:7]

array([4, 5, 6])

In [24]:
x[::2]

array([0, 2, 4, 6, 8])

In [25]:
x[1::2]

array([1, 3, 5, 7, 9])

In [26]:
x[::1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
x[5:: -2]

array([5, 3, 1])

In [28]:
# ----- Multidimensional subarrays ----- #

In [29]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]], dtype=int32)

In [30]:
x2[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]], dtype=int32)

In [31]:
x2[:3, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]], dtype=int32)

In [32]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]], dtype=int32)

In [33]:
# ----- Accessing array rows and columns. ----- #

In [34]:
print(x2[:, 0])

[12  7  1]


In [35]:
print(x2[0, :])

[12  5  2  4]


In [36]:
print(x2[0])

[12  5  2  4]


In [37]:
# ----- Subarrays as no-copy views ----- #

In [38]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [39]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [40]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [41]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [42]:
# ----- Creating copies of arrays ----- #


In [43]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [44]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [45]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [46]:
"""                             Reshaping of Arrays                                  """

'                             Reshaping of Arrays                                  '

In [47]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
x = np.array([1, 2, 3])
x.reshape((1, 3))

array([[1, 2, 3]])

In [49]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [50]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [51]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [52]:
"""                   Array Concatenation and Splitting                                 """

'                   Array Concatenation and Splitting                                 '

In [53]:
# ----- Concatenation of arrays ----- #

In [54]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [55]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [56]:
grid = np.array([[1, 2, 3],
                [4, 5, 6]])
np.concatenate([grid, grid]) # gorizontal birlashtirish

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [57]:
grid = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8]])
np.concatenate([grid, grid], axis= 1) # vertikal birlashtirish

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [5, 6, 7, 8, 5, 6, 7, 8]])

In [58]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
               [6, 5, 4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [59]:
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [60]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8,])
z = np.array([9, 10, 11, 12])
np.concatenate([x, y, z], axis= 0) # gorizontal

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [61]:
x = np.array([[12],
              [34],
              [45],
              [56]])

y = np.array([[90],
              [89],
              [78],
              [56]])

z = np.array([[56],
              [23],
              [12],
              [45]])

np.concatenate([x, y, z], axis = 1)


array([[12, 90, 56],
       [34, 89, 23],
       [45, 78, 12],
       [56, 56, 45]])

In [62]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8,])
z = np.array([9, 10, 11, 12])

np.vstack([x, y ,z])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
np.hstack([x, y, z])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [64]:
x = np.array([[12],
              [34],
              [45],
              [56]])

y = np.array([[90],
              [89],
              [78],
              [56]])

z = np.array([[56],
              [23],
              [12],
              [45]])

np.vstack([x, y, z])

array([[12],
       [34],
       [45],
       [56],
       [90],
       [89],
       [78],
       [56],
       [56],
       [23],
       [12],
       [45]])

In [65]:
np.hstack([x, y, z])

array([[12, 90, 56],
       [34, 89, 23],
       [45, 78, 12],
       [56, 56, 45]])

In [66]:
np.dstack([x, y ,z])

array([[[12, 90, 56]],

       [[34, 89, 23]],

       [[45, 78, 12]],

       [[56, 56, 45]]])

In [67]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8,])
z = np.array([9, 10, 11, 12])

np.dstack([x, y, z])

array([[[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]]])

In [68]:
# ----- Splitting of arrays ----- #

In [69]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9]
x1, x2, x3, = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [4 5] [6 7 8 9]


In [70]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9]
x1, x2, x3, = np.split(x, [1, 8])
print(x1, x2, x3)

[1] [2 3 4 5 6 7 8] [9]


In [71]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [72]:
upper, lower = np.vsplit(grid, [3])

print(upper)
print()
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]]


In [73]:
left, right = np.hsplit(grid, [2])

print(left)
print()
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [74]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [75]:
arr[-1]

np.int64(11)

In [76]:
arr[0]

np.int64(0)

In [77]:
arr[5]

np.int64(5)

In [78]:
arr[-3]

np.int64(9)

In [79]:
x = np.random.randint(1, 12, (3 ,4))
x

array([[ 5,  4,  5,  5],
       [ 9,  5,  4, 11],
       [ 8,  6,  6,  1]], dtype=int32)

In [80]:
x[0, 0]

np.int32(5)

In [81]:
x[-1, -1]

np.int32(1)

In [82]:
x[0, -1]

np.int32(5)

In [83]:
x[-1, 0]

np.int32(8)

In [84]:
x[2, -1]

np.int32(1)

In [85]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [86]:
arr[3: 18: 2]

array([ 3,  5,  7,  9, 11, 13, 15, 17])

In [87]:
arr[:4]

array([0, 1, 2, 3])

In [88]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [89]:
arr[4: 8]

array([4, 5, 6, 7])

In [90]:
arr[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [91]:
arr[::3]

array([ 0,  3,  6,  9, 12, 15, 18])

In [92]:
arr[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [93]:
arr[: 1]

array([0])

In [94]:
x_2D = np.random.randint(1, 20, (4 ,4))
x_2D

array([[18,  6, 10,  4],
       [ 1,  6,  1, 18],
       [19,  5,  3, 17],
       [ 4,  3, 11, 14]], dtype=int32)

In [95]:
x_2D[:2, :3]

array([[18,  6, 10],
       [ 1,  6,  1]], dtype=int32)

In [96]:
x_2D[:, 0]

array([18,  1, 19,  4], dtype=int32)

In [97]:
x_2D[0, :]

array([18,  6, 10,  4], dtype=int32)

In [98]:
x_2D[::-1, ::-1]

array([[14, 11,  3,  4],
       [17,  3,  5, 19],
       [18,  1,  6,  1],
       [ 4, 10,  6, 18]], dtype=int32)

In [99]:
x_2D_sub = x_2D[:2, :2].copy()

In [100]:
x = np.arange(1, 10).reshape((3, 3))
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
x = np.array([1, 2, 3])
x.reshape((1, 3))

array([[1, 2, 3]])

In [102]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [103]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [104]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [105]:
x

array([1, 2, 3])

In [106]:
x_2D

array([[18,  6, 10,  4],
       [ 1,  6,  1, 18],
       [19,  5,  3, 17],
       [ 4,  3, 11, 14]], dtype=int32)

In [107]:
x_2D[0, 0] = 12
x_2D

array([[12,  6, 10,  4],
       [ 1,  6,  1, 18],
       [19,  5,  3, 17],
       [ 4,  3, 11, 14]], dtype=int32)

In [108]:
x_2D[-1:, -1] = 13
x_2D

array([[12,  6, 10,  4],
       [ 1,  6,  1, 18],
       [19,  5,  3, 17],
       [ 4,  3, 11, 13]], dtype=int32)

In [144]:
x = np.arange(1, 20)
y = np.arange(20, 40)
arr1 = np.concatenate([x, y], axis= 0)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39])

In [122]:
x = np.arange(0, 20).reshape(4, 5)
y = np.arange(20, 40).reshape(4, 5)
arr = np.concatenate([x, y], axis = 1)
arr

array([[ 0,  1,  2,  3,  4, 20, 21, 22, 23, 24],
       [ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34],
       [15, 16, 17, 18, 19, 35, 36, 37, 38, 39]])

In [127]:
arr[:4, :4]

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18]])

In [128]:
arr[:: -1, :: -1]

array([[39, 38, 37, 36, 35, 19, 18, 17, 16, 15],
       [34, 33, 32, 31, 30, 14, 13, 12, 11, 10],
       [29, 28, 27, 26, 25,  9,  8,  7,  6,  5],
       [24, 23, 22, 21, 20,  4,  3,  2,  1,  0]])

In [131]:
arr[::1, ::-1]

array([[24, 23, 22, 21, 20,  4,  3,  2,  1,  0],
       [29, 28, 27, 26, 25,  9,  8,  7,  6,  5],
       [34, 33, 32, 31, 30, 14, 13, 12, 11, 10],
       [39, 38, 37, 36, 35, 19, 18, 17, 16, 15]])

In [133]:
arr[::-1, ::1]

array([[15, 16, 17, 18, 19, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34],
       [ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [ 0,  1,  2,  3,  4, 20, 21, 22, 23, 24]])

In [138]:
arr

array([[ 0,  1,  2,  3,  4, 20, 21, 22, 23, 24],
       [ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34],
       [15, 16, 17, 18, 19, 35, 36, 37, 38, 39]])

In [178]:
arr[-1, -1]

np.int32(12)

In [150]:
x = np.arange(9)
y = np.arange(9, 20)

In [151]:
np.hstack([x, y])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [153]:
np.hstack([y, x])

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  0,  1,  2,  3,  4,  5,
        6,  7,  8])

In [154]:
x = np.random.randint(1, 10, (4, 4))
y = np.random.randint(10, 20, (4, 4))

In [ ]:
arr3 = np.vstack([x, y])
arr3

array([[ 1,  8,  6,  1],
       [ 3,  8,  3,  3],
       [ 4,  4,  3,  4],
       [ 5,  2,  3,  2],
       [14, 16, 18, 12],
       [13, 10, 10, 16],
       [10, 16, 13, 13],
       [18, 18, 18, 12]], dtype=int32)

In [159]:
x = np.random.randint(0, 10, (4, 4))
x

array([[8, 0, 8, 5],
       [9, 0, 9, 6],
       [5, 3, 1, 8],
       [0, 4, 9, 6]], dtype=int32)

In [176]:
np.split(x, [2, 4])

[array([[8, 0, 8, 5],
        [9, 0, 9, 6]], dtype=int32),
 array([[5, 3, 1, 8],
        [0, 4, 9, 6]], dtype=int32),
 array([], shape=(0, 4), dtype=int32)]

In [172]:
np.vsplit(x, [3])

[array([[8, 0, 8, 5],
        [9, 0, 9, 6],
        [5, 3, 1, 8]], dtype=int32),
 array([[0, 4, 9, 6]], dtype=int32)]

In [175]:
np.hsplit(x, [1])

[array([[8],
        [9],
        [5],
        [0]], dtype=int32),
 array([[0, 8, 5],
        [0, 9, 6],
        [3, 1, 8],
        [4, 9, 6]], dtype=int32)]